Application\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    email:
      type: string
    forename:
      type: string
    surname:
      type: string
    created:
      type: datetime
